name: "Realizar una consulta y/o solicitar ayuda con errores de programación"
description: "¿Necesitas ayuda con el envío de tu tarea? ¿Te quedaste atascado programando?"
labels: "preguntas"
body:
  - type: checkboxes
    attributes:
      label: Antes de reportar
      description: '`Antes de emitir un issue` verifique que lo que desea preguntar no se encuentre en la [lista de issues](https://github.com/mrg2000/programacion-1-2022-1/issues?q=).'
      options:
        - label: He verificado la lista de issues y lo que deseo preguntar no se encuentra.
          required: true
  - type: markdown
    attributes:
      value: ---
  - type: input
    attributes:
      label: Código de alumno
      description: 'Ingrese su código de alumno.'
      placeholder: 'Ej. 202210341'
    validations:
      required: true
  - type: dropdown
    id: secciones
    attributes:
      label: ¿Cuál es tu sección de teoría?
      options:
        - Teoría 1
        - Teoría 2
        - Teoría 3
        - Teoría 4
    validations:
      required: true
  - type: dropdown
    id: numero-tarea
    attributes:
      label: ¿A qué tarea corresponde esta duda?
      options:
        - Tarea 1.1
        - Tarea 1.2
        - Tarea 2
        - Tarea 3
        - Tarea 4
        - No corresponde a ninguna tarea
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    attributes:
      label: Detalle de la pregunta
      description: Recuerde explicar su duda de la manera más detallada posible, si es necesario incluya `imagenes` y `ejemplos`.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Antes de enviar
      options:
        - label: No estoy compartiendo ninguna solución parcial o total de la tarea.
          required: true
        - label: He agregado todos los labels o etiquetas correspondientes al issue.
          required: true
  - type: markdown
    attributes:
      value: ®UTEC 2022
