name: "Consultas, Preguntas y Dudas"
description: "¿Necesitas ayuda con tu código? ¿Te quedaste atascado programando?"
body:
  - type: checkboxes
    attributes:
      label: Antes de reportar
      description: '`Antes de emitir un issue` verifique que lo que desea preguntar no se encuentre en la lista de issues.'
      options:
        - label: He verificado la lista de issues y lo que deseo preguntar no se encuentra.
          required: true 
  - type: dropdown
    id: secciones
    attributes:
      label: ¿Cuál es tu sección de teoría?
      options:
        - Teoría 1
        - Teoría 2
        - Teoría 3
        - Teoría 4
    validations:
      required: true
  - type: input
    attributes:
      label: Código de alumno
      description: 'Ingrese su código de alumno.'
      placeholder: 'Ej. 202210341'
  - type: textarea
    attributes:
      label: Detalle de la pregunta
      description: Recuerde explicar su duda de la manera más detallada posible, si es necesario incluya `imagenes` y `ejemplos`.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Antes de enviar
      options:
        - label: Mi issue `no contiene código de solución` de ningún tipo.
          required: true
        - label: He agregado todos los `labels` o `etiquetas` correspondientes al issue.
          required: true
  - type: markdown
    attributes:
      value: ®UTEC 2022
